/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package natalia.base.vistas.gui;

/**
 *
 * @author LENOVO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        itemAgregarUsuario = new javax.swing.JMenuItem();
        itemBuscarUsuario = new javax.swing.JMenuItem();
        itemModificarUsuario = new javax.swing.JMenuItem();
        itemEliminarUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesUsuario = new javax.swing.JMenu();
        itemBuscarUsuarioXNombre = new javax.swing.JMenuItem();
        itemBuscarUsuarioXEmail = new javax.swing.JMenuItem();
        itemRecordarContraseñaUsuario = new javax.swing.JMenuItem();
        itemCambiarClaveUsuario = new javax.swing.JMenuItem();
        itemSalirUsuario = new javax.swing.JMenuItem();
        menuActor = new javax.swing.JMenu();
        itemAgregarActor = new javax.swing.JMenuItem();
        itemBuscarActor = new javax.swing.JMenuItem();
        itemModificarActor = new javax.swing.JMenuItem();
        itemEliminarActor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesActor = new javax.swing.JMenu();
        itemBuscarActorXNombre = new javax.swing.JMenuItem();
        itemBuscarActorXEmail = new javax.swing.JMenuItem();
        menuCine = new javax.swing.JMenu();
        itemAgregarCine = new javax.swing.JMenuItem();
        itemBuscarCine = new javax.swing.JMenuItem();
        itemModificarCine = new javax.swing.JMenuItem();
        itemEliminarCine = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesCine = new javax.swing.JMenu();
        itemBuscarCineXNombre = new javax.swing.JMenuItem();
        itemBuscarCineXPais = new javax.swing.JMenuItem();
        menuPelicula = new javax.swing.JMenu();
        itemAgregarPelicula = new javax.swing.JMenuItem();
        itemBuscarPelicula = new javax.swing.JMenuItem();
        itemModificarPelicula = new javax.swing.JMenuItem();
        itemEliminarPelicula = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesPelicula = new javax.swing.JMenu();
        itemBuscarPeliculaXNombre = new javax.swing.JMenuItem();
        itemBuscarPeliculaXActor = new javax.swing.JMenuItem();
        menuPais = new javax.swing.JMenu();
        itemAgregarPais = new javax.swing.JMenuItem();
        itemBuscarPais = new javax.swing.JMenuItem();
        itemModificarPais = new javax.swing.JMenuItem();
        itemEliminarPais = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesPais = new javax.swing.JMenu();
        itemBuscarPaisXNombre = new javax.swing.JMenuItem();
        itemBuscarPorYPais = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:: GESTION DE UN CINE ::..");
        setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/F.png"))); // NOI18N

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Users.png"))); // NOI18N
        menuUsuario.setText("Usuario");
        menuUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        itemAgregarUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/add.png"))); // NOI18N
        itemAgregarUsuario.setText("Agregar...");
        itemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemAgregarUsuario);

        itemBuscarUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Search-icon.png"))); // NOI18N
        itemBuscarUsuario.setText("Buscar...");
        menuUsuario.add(itemBuscarUsuario);

        itemModificarUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/edit.png"))); // NOI18N
        itemModificarUsuario.setText("Modificar...");
        itemModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(itemModificarUsuario);

        itemEliminarUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/delete.png"))); // NOI18N
        itemEliminarUsuario.setText("Eliminar...");
        menuUsuario.add(itemEliminarUsuario);
        menuUsuario.add(jSeparator1);

        subMenuReportesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Report.png"))); // NOI18N
        subMenuReportesUsuario.setText("Reportes...");
        subMenuReportesUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        itemBuscarUsuarioXNombre.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarUsuarioXNombre.setText("Por nombre...");
        subMenuReportesUsuario.add(itemBuscarUsuarioXNombre);

        itemBuscarUsuarioXEmail.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarUsuarioXEmail.setText("Por email...");
        subMenuReportesUsuario.add(itemBuscarUsuarioXEmail);

        menuUsuario.add(subMenuReportesUsuario);

        itemRecordarContraseñaUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemRecordarContraseñaUsuario.setText("Recordar Contraseña...");
        menuUsuario.add(itemRecordarContraseñaUsuario);

        itemCambiarClaveUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemCambiarClaveUsuario.setText("Cambiar Clave...");
        menuUsuario.add(itemCambiarClaveUsuario);

        itemSalirUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemSalirUsuario.setText("Salir...");
        menuUsuario.add(itemSalirUsuario);

        jMenuBar1.add(menuUsuario);

        menuActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Actor.png"))); // NOI18N
        menuActor.setText("Actor");
        menuActor.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        itemAgregarActor.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemAgregarActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/add.png"))); // NOI18N
        itemAgregarActor.setText("Agregar...");
        menuActor.add(itemAgregarActor);

        itemBuscarActor.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Search-icon.png"))); // NOI18N
        itemBuscarActor.setText("Buscar...");
        menuActor.add(itemBuscarActor);

        itemModificarActor.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemModificarActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/edit.png"))); // NOI18N
        itemModificarActor.setText("Modificar...");
        menuActor.add(itemModificarActor);

        itemEliminarActor.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemEliminarActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/delete.png"))); // NOI18N
        itemEliminarActor.setText("Eliminar...");
        menuActor.add(itemEliminarActor);
        menuActor.add(jSeparator2);

        subMenuReportesActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Report.png"))); // NOI18N
        subMenuReportesActor.setText("Reportes...");
        subMenuReportesActor.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        itemBuscarActorXNombre.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarActorXNombre.setText("Por nombre...");
        subMenuReportesActor.add(itemBuscarActorXNombre);

        itemBuscarActorXEmail.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarActorXEmail.setText("Por email...");
        subMenuReportesActor.add(itemBuscarActorXEmail);

        menuActor.add(subMenuReportesActor);

        jMenuBar1.add(menuActor);

        menuCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Cinema.png"))); // NOI18N
        menuCine.setText("Cine");
        menuCine.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        itemAgregarCine.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemAgregarCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/add.png"))); // NOI18N
        itemAgregarCine.setText("Agregar...");
        menuCine.add(itemAgregarCine);

        itemBuscarCine.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Search-icon.png"))); // NOI18N
        itemBuscarCine.setText("Buscar...");
        menuCine.add(itemBuscarCine);

        itemModificarCine.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemModificarCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/edit.png"))); // NOI18N
        itemModificarCine.setText("Modificar...");
        menuCine.add(itemModificarCine);

        itemEliminarCine.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemEliminarCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/delete.png"))); // NOI18N
        itemEliminarCine.setText("Eliminar...");
        menuCine.add(itemEliminarCine);
        menuCine.add(jSeparator3);

        subMenuReportesCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Report.png"))); // NOI18N
        subMenuReportesCine.setText("Reportes...");
        subMenuReportesCine.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        itemBuscarCineXNombre.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarCineXNombre.setText("Por nombre...");
        subMenuReportesCine.add(itemBuscarCineXNombre);

        itemBuscarCineXPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarCineXPais.setText("Por pais...");
        subMenuReportesCine.add(itemBuscarCineXPais);

        menuCine.add(subMenuReportesCine);

        jMenuBar1.add(menuCine);

        menuPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Disney.png"))); // NOI18N
        menuPelicula.setText("Pelicula");
        menuPelicula.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        itemAgregarPelicula.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemAgregarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/add.png"))); // NOI18N
        itemAgregarPelicula.setText("Agregar...");
        menuPelicula.add(itemAgregarPelicula);

        itemBuscarPelicula.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Search-icon.png"))); // NOI18N
        itemBuscarPelicula.setText("Buscar...");
        menuPelicula.add(itemBuscarPelicula);

        itemModificarPelicula.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemModificarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/edit.png"))); // NOI18N
        itemModificarPelicula.setText("Modificar...");
        menuPelicula.add(itemModificarPelicula);

        itemEliminarPelicula.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemEliminarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/delete.png"))); // NOI18N
        itemEliminarPelicula.setText("Eliminar...");
        menuPelicula.add(itemEliminarPelicula);
        menuPelicula.add(jSeparator4);

        subMenuReportesPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Report.png"))); // NOI18N
        subMenuReportesPelicula.setText("Reportes...");
        subMenuReportesPelicula.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        itemBuscarPeliculaXNombre.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarPeliculaXNombre.setText(" Por nombre...");
        subMenuReportesPelicula.add(itemBuscarPeliculaXNombre);

        itemBuscarPeliculaXActor.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarPeliculaXActor.setText(" Por actor...");
        subMenuReportesPelicula.add(itemBuscarPeliculaXActor);

        menuPelicula.add(subMenuReportesPelicula);

        jMenuBar1.add(menuPelicula);

        menuPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Globe.png"))); // NOI18N
        menuPais.setText("Pais");
        menuPais.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        itemAgregarPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemAgregarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/add.png"))); // NOI18N
        itemAgregarPais.setText("Agregar...");
        menuPais.add(itemAgregarPais);

        itemBuscarPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Search-icon.png"))); // NOI18N
        itemBuscarPais.setText("Buscar...");
        menuPais.add(itemBuscarPais);

        itemModificarPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemModificarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/edit.png"))); // NOI18N
        itemModificarPais.setText("Modificar...");
        menuPais.add(itemModificarPais);

        itemEliminarPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemEliminarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/delete.png"))); // NOI18N
        itemEliminarPais.setText("Eliminar...");
        itemEliminarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarPaisActionPerformed(evt);
            }
        });
        menuPais.add(itemEliminarPais);
        menuPais.add(jSeparator5);

        subMenuReportesPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natalia/base/vistas/gui/iconos/Report.png"))); // NOI18N
        subMenuReportesPais.setText("Reportes...");
        subMenuReportesPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        itemBuscarPaisXNombre.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarPaisXNombre.setText(" Por nombre...");
        subMenuReportesPais.add(itemBuscarPaisXNombre);

        itemBuscarPorYPais.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        itemBuscarPorYPais.setText("Buscar por Y...");
        subMenuReportesPais.add(itemBuscarPorYPais);

        menuPais.add(subMenuReportesPais);

        jMenuBar1.add(menuPais);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 672, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemModificarUsuarioActionPerformed

    private void itemEliminarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEliminarPaisActionPerformed

    private void itemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarUsuarioActionPerformed
        VentanaUsuario ventana = new VentanaUsuario(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_itemAgregarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgregarActor;
    private javax.swing.JMenuItem itemAgregarCine;
    private javax.swing.JMenuItem itemAgregarPais;
    private javax.swing.JMenuItem itemAgregarPelicula;
    private javax.swing.JMenuItem itemAgregarUsuario;
    private javax.swing.JMenuItem itemBuscarActor;
    private javax.swing.JMenuItem itemBuscarActorXEmail;
    private javax.swing.JMenuItem itemBuscarActorXNombre;
    private javax.swing.JMenuItem itemBuscarCine;
    private javax.swing.JMenuItem itemBuscarCineXNombre;
    private javax.swing.JMenuItem itemBuscarCineXPais;
    private javax.swing.JMenuItem itemBuscarPais;
    private javax.swing.JMenuItem itemBuscarPaisXNombre;
    private javax.swing.JMenuItem itemBuscarPelicula;
    private javax.swing.JMenuItem itemBuscarPeliculaXActor;
    private javax.swing.JMenuItem itemBuscarPeliculaXNombre;
    private javax.swing.JMenuItem itemBuscarPorYPais;
    private javax.swing.JMenuItem itemBuscarUsuario;
    private javax.swing.JMenuItem itemBuscarUsuarioXEmail;
    private javax.swing.JMenuItem itemBuscarUsuarioXNombre;
    private javax.swing.JMenuItem itemCambiarClaveUsuario;
    private javax.swing.JMenuItem itemEliminarActor;
    private javax.swing.JMenuItem itemEliminarCine;
    private javax.swing.JMenuItem itemEliminarPais;
    private javax.swing.JMenuItem itemEliminarPelicula;
    private javax.swing.JMenuItem itemEliminarUsuario;
    private javax.swing.JMenuItem itemModificarActor;
    private javax.swing.JMenuItem itemModificarCine;
    private javax.swing.JMenuItem itemModificarPais;
    private javax.swing.JMenuItem itemModificarPelicula;
    private javax.swing.JMenuItem itemModificarUsuario;
    private javax.swing.JMenuItem itemRecordarContraseñaUsuario;
    private javax.swing.JMenuItem itemSalirUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu menuActor;
    private javax.swing.JMenu menuCine;
    private javax.swing.JMenu menuPais;
    private javax.swing.JMenu menuPelicula;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu subMenuReportesActor;
    private javax.swing.JMenu subMenuReportesCine;
    private javax.swing.JMenu subMenuReportesPais;
    private javax.swing.JMenu subMenuReportesPelicula;
    private javax.swing.JMenu subMenuReportesUsuario;
    // End of variables declaration//GEN-END:variables
}
